# Eduskript Development Environment Setup for Windows (PowerShell)
# Automatically configures PostgreSQL via Docker and Next.js

$ErrorActionPreference = "Stop"

# Colors
function Write-Success { param($msg) Write-Host "✓ $msg" -ForegroundColor Green }
function Write-Info { param($msg) Write-Host "→ $msg" -ForegroundColor Cyan }
function Write-Warning { param($msg) Write-Host "⚠ $msg" -ForegroundColor Yellow }
function Write-Error { param($msg) Write-Host "✗ $msg" -ForegroundColor Red }
function Write-Header { param($msg) Write-Host "`n$msg" -ForegroundColor Blue }

Write-Header "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Header "    Eduskript Development Environment Setup"
Write-Header "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""

# Check if Docker is installed and running
Write-Info "[1/8] Checking Docker..."
try {
    $null = docker --version 2>$null
    $null = docker info 2>$null
    Write-Success "Docker is installed and running"
} catch {
    Write-Error "Docker is not installed or not running"
    Write-Host ""
    Write-Warning "Please install Docker Desktop from:"
    Write-Host "  https://www.docker.com/products/docker-desktop/"
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}
Write-Host ""

# Check if node_modules exists
Write-Info "[2/8] Checking dependencies..."
if (-not (Test-Path "node_modules")) {
    Write-Info "Installing dependencies (first time setup)..."
    pnpm install
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to install dependencies"
        Read-Host "Press Enter to exit"
        exit 1
    }
    Write-Success "Dependencies installed"
} else {
    Write-Success "Dependencies already installed"
}
Write-Host ""

# Check if .env.local exists
Write-Info "[3/8] Configuring environment..."
$regenerate = $false
if (Test-Path ".env.local") {
    Write-Warning ".env.local already exists"
    $response = Read-Host "Do you want to regenerate it? (y/N)"
    $regenerate = $response -eq 'y' -or $response -eq 'Y'
}

if (-not (Test-Path ".env.local") -or $regenerate) {
    Write-Info "Generating .env.local..."

    # Generate a random secret
    $secret = "dev-secret-$(Get-Random)-$(Get-Random)-$(Get-Random)"

    $envContent = @"
# Auto-generated by setup-dev.ps1
# This file is specific to this development environment

# PostgreSQL Configuration
POSTGRES_PORT=5432
POSTGRES_CONTAINER_NAME=eduskript-postgres-dev
POSTGRES_VOLUME_NAME=eduskript_postgres_data

# Database URL
DATABASE_URL="postgresql://postgres:password@localhost:5432/eduskript_dev"

# Next.js Configuration
PORT=3000
NEXTAUTH_URL=http://localhost:3000

# NextAuth Secret
NEXTAUTH_SECRET=$secret
"@

    $envContent | Out-File -FilePath ".env.local" -Encoding UTF8
    Write-Success "Created .env.local"
} else {
    Write-Success "Using existing .env.local"
}
Write-Host ""

# Start PostgreSQL container
Write-Info "[4/8] Setting up PostgreSQL container..."
$containerExists = docker ps -a --format "{{.Names}}" | Select-String -Pattern "^eduskript-postgres-dev$"
if (-not $containerExists) {
    Write-Info "Creating PostgreSQL container..."
    docker compose -f docker-compose.local.yml up -d
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to start PostgreSQL container"
        Read-Host "Press Enter to exit"
        exit 1
    }
    Write-Success "Container created and started"
} else {
    $containerRunning = docker ps --format "{{.Names}}" | Select-String -Pattern "^eduskript-postgres-dev$"
    if (-not $containerRunning) {
        Write-Info "Starting existing container..."
        docker start eduskript-postgres-dev | Out-Null
        Write-Success "Container started"
    } else {
        Write-Success "Container is already running"
    }
}
Write-Host ""

# Wait for PostgreSQL to be ready
Write-Info "[5/8] Waiting for PostgreSQL to be ready..."
$counter = 0
while ($counter -lt 30) {
    $ready = docker exec eduskript-postgres-dev pg_isready -U postgres 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Success "PostgreSQL is ready"
        break
    }
    $counter++
    Start-Sleep -Seconds 1
}
if ($counter -ge 30) {
    Write-Error "PostgreSQL failed to start after 30 seconds"
    Read-Host "Press Enter to exit"
    exit 1
}
Write-Host ""

# Generate Prisma client
Write-Info "[6/8] Generating Prisma client..."
pnpm db:generate | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to generate Prisma client"
    Read-Host "Press Enter to exit"
    exit 1
}
Write-Success "Prisma client generated"
Write-Host ""

# Run database migrations
Write-Info "[7/8] Running database migrations..."
pnpm prisma migrate deploy | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Warning "Migration failed - database might already be up to date"
} else {
    Write-Success "Migrations applied"
}
Write-Host ""

# Seed admin user
Write-Info "[8/8] Seeding admin user..."
node prisma/seed-admin-sql.mjs | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Warning "Admin user might already exist"
} else {
    Write-Success "Admin user seeded"
}
Write-Host ""

# Print success message
Write-Header "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host "✓ " -ForegroundColor Green -NoNewline
Write-Host "Development Environment Ready!" -ForegroundColor Green
Write-Header "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""

Write-Host "PostgreSQL:" -ForegroundColor Blue
Write-Host "  Port:      " -NoNewline; Write-Host "5432" -ForegroundColor Yellow
Write-Host "  Container: " -NoNewline; Write-Host "eduskript-postgres-dev" -ForegroundColor Yellow
Write-Host "  Database:  " -NoNewline; Write-Host "eduskript_dev" -ForegroundColor Yellow
Write-Host ""

Write-Host "Next.js:" -ForegroundColor Blue
Write-Host "  Port:      " -NoNewline; Write-Host "3000" -ForegroundColor Yellow
Write-Host "  URL:       " -NoNewline; Write-Host "http://localhost:3000" -ForegroundColor Yellow
Write-Host ""

Write-Host "Admin Credentials:" -ForegroundColor Blue
Write-Host "  Email:     " -NoNewline; Write-Host "eduadmin@eduskript.org" -ForegroundColor Yellow
Write-Host "  Password:  " -NoNewline; Write-Host "letseducate" -ForegroundColor Yellow
Write-Host ""

Write-Host "Next Steps:" -ForegroundColor Blue
Write-Host "  1. Start dev server:  " -NoNewline; Write-Host "pnpm dev" -ForegroundColor Green
Write-Host "  2. Open browser:      " -NoNewline; Write-Host "http://localhost:3000" -ForegroundColor Green
Write-Host "  3. Sign in with admin credentials above"
Write-Host ""

Write-Host "Managing PostgreSQL:" -ForegroundColor Blue
Write-Host "  View logs:    " -NoNewline; Write-Host "docker logs eduskript-postgres-dev" -ForegroundColor Green
Write-Host "  Stop:         " -NoNewline; Write-Host "docker stop eduskript-postgres-dev" -ForegroundColor Green
Write-Host "  Start:        " -NoNewline; Write-Host "docker start eduskript-postgres-dev" -ForegroundColor Green
Write-Host "  Remove:       " -NoNewline; Write-Host "docker compose -f docker-compose.local.yml down -v" -ForegroundColor Green
Write-Host ""

Read-Host "Press Enter to exit"
