@echo off
setlocal enabledelayedexpansion

REM Eduskript Development Environment Setup for Windows
REM Automatically configures PostgreSQL via Docker and Next.js

echo ========================================
echo   Eduskript Development Environment Setup
echo ========================================
echo.

REM Check if Docker is installed and running
echo [1/8] Checking Docker...
docker --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Docker is not installed or not in PATH
    echo.
    echo Please install Docker Desktop from:
    echo   https://www.docker.com/products/docker-desktop/
    echo.
    pause
    exit /b 1
)

docker info >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Docker is not running
    echo.
    echo Please start Docker Desktop and run this script again
    pause
    exit /b 1
)

echo [OK] Docker is installed and running
echo.

REM Check if node_modules exists, if not run pnpm install
echo [2/8] Checking dependencies...
if not exist "node_modules\" (
    echo Installing dependencies ^(first time setup^)...
    call pnpm install
    if errorlevel 1 (
        echo [ERROR] Failed to install dependencies
        pause
        exit /b 1
    )
    echo [OK] Dependencies installed
) else (
    echo [OK] Dependencies already installed
)
echo.

REM Check if .env.local exists
echo [3/8] Configuring environment...
if exist ".env.local" (
    echo [INFO] .env.local already exists
    set /p "REGENERATE=Do you want to regenerate it? (y/N): "
    if /i "!REGENERATE!"=="y" (
        goto :generate_env
    ) else (
        echo [OK] Using existing .env.local
        goto :skip_env
    )
)

:generate_env
echo Generating .env.local...

REM Generate a simple secret (Windows doesn't have openssl easily available)
set "NEXTAUTH_SECRET=dev-secret-%RANDOM%-%RANDOM%-%RANDOM%"

REM Create .env.local
(
echo # Auto-generated by setup-dev.bat
echo # This file is specific to this development environment
echo.
echo # PostgreSQL Configuration
echo POSTGRES_PORT=5432
echo POSTGRES_CONTAINER_NAME=eduskript-postgres-dev
echo POSTGRES_VOLUME_NAME=eduskript_postgres_data
echo.
echo # Database URL
echo DATABASE_URL="postgresql://postgres:password@localhost:5432/eduskript_dev"
echo.
echo # Next.js Configuration
echo PORT=3000
echo NEXTAUTH_URL=http://localhost:3000
echo.
echo # NextAuth Secret
echo NEXTAUTH_SECRET=!NEXTAUTH_SECRET!
) > .env.local

echo [OK] Created .env.local
echo.

:skip_env

REM Start PostgreSQL container
echo [4/8] Setting up PostgreSQL container...
docker ps -a --format "{{.Names}}" | findstr /x "eduskript-postgres-dev" >nul
if errorlevel 1 (
    echo Creating PostgreSQL container...
    docker compose -f docker-compose.local.yml up -d
    if errorlevel 1 (
        echo [ERROR] Failed to start PostgreSQL container
        pause
        exit /b 1
    )
    echo [OK] Container created and started
) else (
    docker ps --format "{{.Names}}" | findstr /x "eduskript-postgres-dev" >nul
    if errorlevel 1 (
        echo Starting existing container...
        docker start eduskript-postgres-dev >nul
        echo [OK] Container started
    ) else (
        echo [OK] Container is already running
    )
)
echo.

REM Wait for PostgreSQL to be ready
echo [5/8] Waiting for PostgreSQL to be ready...
set COUNTER=0
:wait_postgres
docker exec eduskript-postgres-dev pg_isready -U postgres >nul 2>&1
if errorlevel 1 (
    set /a COUNTER+=1
    if !COUNTER! GEQ 30 (
        echo [ERROR] PostgreSQL failed to start after 30 seconds
        pause
        exit /b 1
    )
    timeout /t 1 /nobreak >nul
    goto :wait_postgres
)
echo [OK] PostgreSQL is ready
echo.

REM Generate Prisma client
echo [6/8] Generating Prisma client...
call pnpm db:generate >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Failed to generate Prisma client
    pause
    exit /b 1
)
echo [OK] Prisma client generated
echo.

REM Run database migrations
echo [7/8] Running database migrations...
call pnpm prisma migrate deploy >nul 2>&1
if errorlevel 1 (
    echo [WARNING] Migration failed - database might already be up to date
) else (
    echo [OK] Migrations applied
)
echo.

REM Seed admin user
echo [8/8] Seeding admin user...
call node prisma/seed-admin-sql.mjs >nul 2>&1
if errorlevel 1 (
    echo [WARNING] Admin user might already exist
) else (
    echo [OK] Admin user seeded
)
echo.

REM Print success message
echo ========================================
echo   Development Environment Ready!
echo ========================================
echo.
echo PostgreSQL:
echo   Port:      5432
echo   Container: eduskript-postgres-dev
echo   Database:  eduskript_dev
echo.
echo Next.js:
echo   Port:      3000
echo   URL:       http://localhost:3000
echo.
echo Admin Credentials:
echo   Email:     eduadmin@eduskript.org
echo   Password:  letseducate
echo.
echo Next Steps:
echo   1. Start dev server:  pnpm dev
echo   2. Open browser:      http://localhost:3000
echo   3. Sign in with admin credentials above
echo.
echo Managing PostgreSQL:
echo   View logs:    docker logs eduskript-postgres-dev
echo   Stop:         docker stop eduskript-postgres-dev
echo   Start:        docker start eduskript-postgres-dev
echo   Remove:       docker compose -f docker-compose.local.yml down -v
echo.
echo ========================================
pause
